In [190]:
from collections import namedtuple
import numpy as np

Point = namedtuple('Point', ['x', 'y'])

def parse_point(s):
    return [int(n) for n in s.strip().split(',')]

def parse_vents(buf):
    # Dimensions: vents x 2 (start, end) x 2 (x, y)
    vents = []
    for l in buf:
        if not l.strip(): continue
        vents.append([parse_point(p) for p in l.split('->')])
    return np.array(vents, dtype=int)

def coord_range(x, y):
    """Inclusive range that work even if y < x"""
    return range(x, y-1, -1) if x > y else range(x, y+1)        

def map_vents(vents, allow_diagonal=False):
    xmax = vents[..., 0].max() + 1
    ymax = vents[..., 1].max() + 1
    grid = np.zeros((xmax, ymax), dtype=int)
    for (x1, y1), (x2, y2) in vents:
        if not ((x1 == x2 or y1 == y2) or
                (allow_diagonal and abs(x1 - x2) == abs(y1 - y2))):
            continue
        grid[coord_range(y1, y2), coord_range(x1, x2)] += 1
    return grid

def num_overlapping(grid):
    print(grid)
    return (grid > 1).sum()

In [188]:
from io import StringIO

test_input = StringIO("""
0,9 -> 5,9
8,0 -> 0,8
9,4 -> 3,4
2,2 -> 2,1
7,0 -> 7,4
6,4 -> 2,0
0,9 -> 2,9
3,4 -> 1,4
0,0 -> 8,8
5,5 -> 8,2
""")

In [186]:
num_overlapping(map_vents(parse_vents(test_input), allow_diagonal=False))

[[0 0 0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 1 1 2 1 1 1 2 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [2 2 2 1 1 1 0 0 0 0]]


5

In [189]:
num_overlapping(map_vents(parse_vents(test_input), allow_diagonal=True))

[[1 0 1 0 0 0 0 1 1 0]
 [0 1 1 1 0 0 0 2 0 0]
 [0 0 2 0 1 0 1 1 1 0]
 [0 0 0 1 0 2 0 2 0 0]
 [0 1 1 2 3 1 3 2 1 1]
 [0 0 0 1 0 2 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 1 0]
 [2 2 2 1 1 1 0 0 0 0]]


12

In [191]:
with open('../data/day05.txt') as infile:
    vents = parse_vents(infile)
    grid = map_vents_straight(vents)
    print('[p1] Num overlaps:', num_overlapping(grid))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[p1] Num overlaps: 4421
